# Generated by Django 4.2.5 on 2023-09-05 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_department'),
    ]

    operations = [
        migrations.DeleteModel(
            name='department',
        ),
    ]
