# Generated by Django 4.2.5 on 2023-09-05 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_delete_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='size',
            field=models.IntegerField(default=1),
        ),
    ]
