# Generated by Django 2.0 on 2023-09-06 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depart_name', models.CharField(max_length=30, verbose_name='部门名称')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=25, verbose_name='姓名')),
                ('user_gender', models.SmallIntegerField(choices=[(0, '女'), (1, '男')], verbose_name='性别')),
                ('user_age', models.IntegerField(verbose_name='年龄')),
                ('user_address', models.CharField(max_length=30, verbose_name='家庭地址')),
                ('user_email', models.CharField(max_length=30, verbose_name='邮箱')),
                ('depart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.Departments')),
            ],
        ),
    ]
