# Generated by Django 2.0 on 2023-09-06 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Other',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.IntegerField(verbose_name='变量')),
                ('page', models.IntegerField(verbose_name='页数')),
            ],
        ),
    ]
