# Generated by Django 2.0 on 2023-09-07 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_other'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='user_entry_time',
            field=models.DateTimeField(default='2021-01-02', verbose_name='入职时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='user_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='工资'),
        ),
    ]
