# Generated by Django 2.0 on 2023-09-07 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0003_auto_20230907_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='depart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.Departments', verbose_name='部门'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_entry_time',
            field=models.DateField(verbose_name='入职时间'),
        ),
    ]
