# Generated by Django 2.0 on 2023-09-07 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0004_auto_20230907_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='user_entry_time',
            field=models.DateTimeField(verbose_name='入职时间'),
        ),
    ]
