# Generated by Django 2.0 on 2023-09-09 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0006_prettynum'),
    ]

    operations = [
        migrations.AddField(
            model_name='departments',
            name='depart_introduce',
            field=models.CharField(blank=True, default='你好', max_length=50, null=True, verbose_name='部门介绍'),
        ),
        migrations.AlterField(
            model_name='prettynum',
            name='level',
            field=models.SmallIntegerField(choices=[(0, '未评级'), (1, '一星'), (2, '二星'), (3, '三星'), (4, '四星'), (5, '五星')], default=0, verbose_name='级别'),
        ),
        migrations.AlterField(
            model_name='prettynum',
            name='price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='价格'),
        ),
    ]
