# Generated by Django 2.0 on 2023-09-09 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0007_auto_20230909_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='departments',
            name='depart_images',
            field=models.CharField(blank=True, default='Hello', max_length=100, null=True, verbose_name='部门图片'),
        ),
    ]
