# Generated by Django 2.0 on 2023-09-09 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0008_departments_depart_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departments',
            name='depart_images',
            field=models.CharField(blank=True, default='Hello', max_length=255, null=True, verbose_name='部门图片'),
        ),
    ]
