# Generated by Django 2.0 on 2023-09-09 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0009_auto_20230909_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='departments',
            name='depart_principal',
            field=models.CharField(blank=True, default='明明', max_length=30, null=True, verbose_name='部门负责人'),
        ),
    ]
