# Generated by Django 2.0 on 2023-09-10 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0010_departments_depart_principal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='名称')),
                ('url', models.CharField(blank=True, default='notImages', max_length=255, null=True, verbose_name='链接')),
            ],
        ),
    ]
