# Generated by Django 2.0 on 2023-09-10 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0011_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, verbose_name='管理员姓名')),
                ('password', models.CharField(max_length=30, verbose_name='管理员密码')),
            ],
        ),
    ]
