# Generated by Django 2.0 on 2023-09-12 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0016_auto_20230912_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.Admin', verbose_name='负责人'),
        ),
    ]
