# Generated by Django 2.0 on 2023-09-13 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0017_auto_20230912_2056'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100, verbose_name='订单编号')),
                ('order_name', models.CharField(max_length=100, verbose_name='订单名称')),
                ('order_price', models.IntegerField(max_length=100, verbose_name='订单价格')),
                ('order_static', models.SmallIntegerField(choices=[('1', '未支付'), ('2', '已支付')], default=1, verbose_name='订单状态')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.Admin', verbose_name='订单负责人')),
            ],
        ),
    ]
