# Generated by Django 2.0 on 2023-09-13 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0018_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_static',
            field=models.SmallIntegerField(choices=[(1, '未支付'), (2, '已支付')], default=1, verbose_name='订单状态'),
        ),
    ]
