# Generated by Django 2.0 on 2023-09-14 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0020_auto_20230913_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='departments',
            name='depart_person',
            field=models.IntegerField(default=100, verbose_name='部门人数'),
        ),
    ]
